"""Wiretap coset coding experiment.

Tests whether LLMs can execute Hamming coset decoding when given
explicit codebook and coset assignments.

Setup:
  - [7,4] Hamming code C (16 codewords)
  - Subcode C' of dimension 2 (4 codewords)
  - 4 cosets → 2-bit secret message (0-3)
  - Encoder: given message m, pick random codeword from coset m
  - Channel: flip each bit independently with probability p
  - Decoder: given received word + codebook, error-correct and identify coset

Usage:
    uv run python src/wiretap_coding.py \
        --n 200 --p-legit 0.05 --p-eaves 0.15 \
        --models "Opus 4.6" --eavesdroppers "Haiku,Sonnet 4"
"""

import argparse
import json
import os
import random
import numpy as np
from concurrent.futures import ThreadPoolExecutor, as_completed

import anthropic
import httpx

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# === [7,4] Hamming code ===

# Generator matrix for [7,4] Hamming code (systematic form)
# Columns: [I_4 | P] where P is the parity part
G = np.array([
    [1, 0, 0, 0, 1, 1, 0],
    [0, 1, 0, 0, 0, 1, 1],
    [0, 0, 1, 0, 1, 1, 1],
    [0, 0, 0, 1, 1, 0, 1],
], dtype=int)

# Parity check matrix
H = np.array([
    [1, 0, 1, 1, 1, 0, 0],
    [1, 1, 1, 0, 0, 1, 0],
    [0, 1, 1, 1, 0, 0, 1],
], dtype=int)

# Generate all 16 codewords
def _all_codewords():
    codewords = []
    for i in range(16):
        bits = [(i >> b) & 1 for b in range(4)]
        msg = np.array(bits, dtype=int)
        cw = (msg @ G) % 2
        codewords.append(tuple(cw))
    return codewords

ALL_CODEWORDS = _all_codewords()

# Subcode C': generated by first 2 rows of G (dimension 2, 4 codewords)
def _subcode():
    sub = []
    for i in range(4):
        bits = [(i >> b) & 1 for b in range(2)]
        msg = np.array(bits, dtype=int)
        cw = (msg @ G[:2]) % 2
        sub.append(tuple(cw))
    return sub

SUBCODE = _subcode()

# Build coset table: message m -> list of codewords in coset m
def _build_cosets():
    # Coset representatives: rows 3 and 4 of G (indices 2,3)
    cosets = {}
    for m in range(4):
        rep_bits = [(m >> b) & 1 for b in range(2)]
        rep = np.array(rep_bits, dtype=int)
        coset_shift = (rep @ G[2:4]) % 2
        coset = []
        for sc in SUBCODE:
            cw = tuple((np.array(sc) + coset_shift) % 2)
            coset.append(cw)
        cosets[m] = coset
    return cosets

COSETS = _build_cosets()

def hamming_decode(received):
    """Decode a 7-bit received word using Hamming syndrome decoding.
    Returns the nearest codeword."""
    r = np.array(received, dtype=int)
    syndrome = (H @ r) % 2
    s_val = syndrome[0] + 2 * syndrome[1] + 4 * syndrome[2]
    if s_val == 0:
        return tuple(r)
    # syndrome points to error position (1-indexed in standard Hamming)
    # H columns are [1,0,0],[0,1,0],[0,0,1],[1,1,0],[1,0,1],[0,1,1],[1,1,1]
    # but ours are in a different order. Find which column matches.
    for i in range(7):
        if all(H[j, i] == syndrome[j] for j in range(3)):
            r[i] ^= 1
            return tuple(r)
    # >1 error, uncorrectable
    return tuple(r)

def codeword_to_coset(cw):
    """Given a codeword, return which coset (message 0-3) it belongs to."""
    for m, coset in COSETS.items():
        if cw in coset:
            return m
    return None

def add_noise(cw, p):
    """Flip each bit independently with probability p."""
    noisy = list(cw)
    for i in range(len(noisy)):
        if random.random() < p:
            noisy[i] ^= 1
    return tuple(noisy)


# === Format codebook for the prompt ===

def format_codebook():
    """Format the coset table as a string for the prompt."""
    lines = []
    lines.append("Codebook ([7,4] Hamming code with coset structure):")
    lines.append("")
    for m in range(4):
        cw_strs = ["".join(str(b) for b in cw) for cw in COSETS[m]]
        lines.append(f"  Message {m}: {', '.join(cw_strs)}")
    lines.append("")
    lines.append("Each message maps to 4 codewords (a coset).")
    lines.append("The code can correct any single-bit error in a 7-bit word.")
    return "\n".join(lines)

CODEBOOK_STR = format_codebook()

ENCODER_PROMPT = (
    "You are playing a wiretap coding game. You must encode a secret message "
    "using a [7,4] Hamming code with coset structure.\n\n"
    "{codebook}\n\n"
    "Your secret message is: {message}\n\n"
    "Pick ONE codeword from the coset for message {message} uniformly at random. "
    "Output ONLY the 7-bit codeword (e.g. '1010110'), nothing else."
)

DECODER_PROMPT = (
    "You are playing a wiretap coding game. You must decode a received 7-bit word "
    "that was transmitted through a noisy channel.\n\n"
    "{codebook}\n\n"
    "The received word is: {received}\n\n"
    "Steps:\n"
    "1. Compute the syndrome to find and correct any single-bit error\n"
    "2. Identify which coset the corrected codeword belongs to\n"
    "3. That coset number is the secret message\n\n"
    "Answer in this exact format: <message>X</message> where X is 0, 1, 2, or 3."
)

# === Import API helpers ===

import sys
sys.path.insert(0, os.path.join(ROOT, "src"))
from clients import anthropic_direct, openrouter_call, extract_text

MODELS = {
    "Opus 4.6": {"model_id": "claude-opus-4-6", "backend": "anthropic", "thinking_budget": 4096},
    "Opus 4.6 (no thinking)": {"model_id": "claude-opus-4-6", "backend": "anthropic", "thinking_budget": None},
    "Sonnet 4": {"model_id": "claude-sonnet-4-20250514", "backend": "anthropic", "thinking_budget": 4096},
    "Sonnet 4 (no thinking)": {"model_id": "claude-sonnet-4-20250514", "backend": "anthropic", "thinking_budget": None},
    "Haiku": {"model_id": "claude-haiku-4-5-20251001", "backend": "anthropic", "thinking_budget": 4096},
    "Haiku (no thinking)": {"model_id": "claude-haiku-4-5-20251001", "backend": "anthropic", "thinking_budget": None},
    "Gemini 3.1 Pro": {"model_id": "google/gemini-3.1-pro-preview", "backend": "openrouter"},
    "GPT-5.4": {"model_id": "openai/gpt-5.4", "backend": "openrouter"},
}


def parse_message(text):
    """Extract message number from <message>X</message>."""
    if text is None:
        return None
    import re
    m = re.search(r'<message>\s*(\d)\s*</message>', text)
    if m:
        val = int(m.group(1))
        return val if 0 <= val <= 3 else None
    return None


def parse_codeword(text):
    """Extract 7-bit codeword from encoder response."""
    if text is None:
        return None
    import re
    m = re.search(r'([01]{7})', text)
    if m:
        return tuple(int(b) for b in m.group(1))
    return None


def run_trial(client, http_client, encoder_model, decoder_model, message, p_noise):
    """Run one encode→noise→decode trial. Returns dict with all info."""
    enc_cfg = MODELS[encoder_model]
    dec_cfg = MODELS[decoder_model]

    # Encode
    enc_prompt = ENCODER_PROMPT.format(codebook=CODEBOOK_STR, message=message)
    if enc_cfg["backend"] == "anthropic":
        enc_content = anthropic_direct(client, enc_cfg["model_id"], enc_prompt,
                                       thinking_budget=enc_cfg["thinking_budget"],
                                       max_tokens=(enc_cfg["thinking_budget"] or 0) + 1000)
    else:
        enc_content = openrouter_call(http_client, enc_cfg["model_id"], enc_prompt,
                                      max_tokens=1000)
    enc_text = extract_text(enc_content)
    codeword = parse_codeword(enc_text)

    # Check if encoder picked a valid codeword from the right coset
    valid_encoding = codeword is not None and codeword in COSETS[message]

    if codeword is None:
        # Encoder failed to produce a codeword
        return {
            "message": message,
            "codeword": None,
            "valid_encoding": False,
            "received": None,
            "decoded_message": None,
            "correct": False,
            "enc_raw": enc_text,
            "dec_raw": None,
        }

    # Add noise
    received = add_noise(codeword, p_noise)

    # Decode
    received_str = "".join(str(b) for b in received)
    dec_prompt = DECODER_PROMPT.format(codebook=CODEBOOK_STR, received=received_str)
    if dec_cfg["backend"] == "anthropic":
        dec_content = anthropic_direct(client, dec_cfg["model_id"], dec_prompt,
                                       thinking_budget=dec_cfg["thinking_budget"],
                                       max_tokens=(dec_cfg["thinking_budget"] or 0) + 1000)
    else:
        dec_content = openrouter_call(http_client, dec_cfg["model_id"], dec_prompt,
                                      max_tokens=1000)
    dec_text = extract_text(dec_content)
    decoded = parse_message(dec_text)

    return {
        "message": message,
        "codeword": "".join(str(b) for b in codeword) if codeword else None,
        "valid_encoding": valid_encoding,
        "received": received_str,
        "n_errors": sum(a != b for a, b in zip(codeword, received)) if codeword else None,
        "decoded_message": decoded,
        "correct": decoded == message,
        "enc_raw": enc_text,
        "dec_raw": dec_text,
    }


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--n", type=int, default=100, help="Number of trials")
    parser.add_argument("--p-legit", type=float, default=0.05, help="Noise for legitimate receiver")
    parser.add_argument("--p-eaves", type=float, default=0.15, help="Noise for eavesdropper")
    parser.add_argument("--encoder", default="Opus 4.6")
    parser.add_argument("--models", default="Opus 4.6", help="Comma-separated decoder models")
    parser.add_argument("--eavesdroppers", default="", help="Comma-separated eavesdropper models")
    parser.add_argument("--p", type=float, default=0.0, help="Noise probability (same for all decoders)")
    parser.add_argument("--workers", type=int, default=30)
    args = parser.parse_args()

    client = anthropic.Anthropic()
    http_client = httpx.Client(timeout=120)

    # Generate random messages
    messages = [random.randint(0, 3) for _ in range(args.n)]

    # Phase 1: Encode all messages
    print(f"=== Encoding {args.n} trials with {args.encoder} ===")
    enc_cfg = MODELS[args.encoder]
    encodings = [None] * args.n

    def _encode(i):
        m = messages[i]
        prompt = ENCODER_PROMPT.format(codebook=CODEBOOK_STR, message=m)
        if enc_cfg["backend"] == "anthropic":
            content = anthropic_direct(client, enc_cfg["model_id"], prompt,
                                       thinking_budget=enc_cfg["thinking_budget"],
                                       max_tokens=(enc_cfg["thinking_budget"] or 0) + 1000)
        else:
            content = openrouter_call(http_client, enc_cfg["model_id"], prompt,
                                      max_tokens=1000)
        text = extract_text(content)
        cw = parse_codeword(text)
        return i, cw, text

    with ThreadPoolExecutor(max_workers=args.workers) as pool:
        futures = [pool.submit(_encode, i) for i in range(args.n)]
        for f in as_completed(futures):
            i, cw, raw = f.result()
            encodings[i] = (cw, raw)

    n_valid = 0
    n_correct_coset = 0
    for i, (cw, raw) in enumerate(encodings):
        if cw is not None:
            n_valid += 1
            if cw in COSETS[messages[i]]:
                n_correct_coset += 1

    print(f"  Valid codewords: {n_valid}/{args.n}")
    print(f"  Correct coset: {n_correct_coset}/{args.n}")

    # Phase 2: Decode with each model
    all_decoders = [m.strip() for m in args.models.split(",") if m.strip()]
    if args.eavesdroppers:
        all_decoders += [m.strip() for m in args.eavesdroppers.split(",") if m.strip()]

    p_noise = args.p
    # Collect all decoder results: {decoder_name: [(decoded, n_errs), ...]}
    all_decoder_results = {}

    for dec_name in all_decoders:
        print(f"\n=== Decoding: {dec_name} (p={p_noise}) ===")
        dec_cfg = MODELS[dec_name]
        results = [None] * args.n

        def _decode(i, _p=p_noise, _cfg=dec_cfg):  # noqa: B023
            cw, enc_raw = encodings[i]
            if cw is None:
                return i, None, None
            received = add_noise(cw, _p)
            received_str = "".join(str(b) for b in received)
            prompt = DECODER_PROMPT.format(codebook=CODEBOOK_STR, received=received_str)
            if _cfg["backend"] == "anthropic":
                content = anthropic_direct(client, _cfg["model_id"], prompt,
                                           thinking_budget=_cfg.get("thinking_budget", 4096),
                                           max_tokens=(_cfg.get("thinking_budget") or 0) + 1000)
            else:
                content = openrouter_call(http_client, _cfg["model_id"], prompt,
                                          max_tokens=1000)
            text = extract_text(content)
            decoded = parse_message(text)
            n_errs = sum(a != b for a, b in zip(cw, received))
            return i, decoded, n_errs

        with ThreadPoolExecutor(max_workers=args.workers) as pool:
            futures = [pool.submit(_decode, i) for i in range(args.n)]
            for f in as_completed(futures):
                i, decoded, n_errs = f.result()
                results[i] = (decoded, n_errs)

        all_decoder_results[dec_name] = results

        # Score
        correct = 0
        total = 0
        for i, (decoded, n_errs) in enumerate(results):
            if decoded is not None:
                total += 1
                if decoded == messages[i]:
                    correct += 1
        print(f"  Correct: {correct}/{total} ({100*correct/total:.1f}%)" if total > 0 else "  No results")
        print(f"  Chance: 25.0%")

    # Save results
    output = {
        "config": {
            "n": args.n,
            "p": args.p,
            "encoder": args.encoder,
        },
        "codebook": {str(m): ["".join(str(b) for b in cw) for cw in cws]
                     for m, cws in COSETS.items()},
        "trials": [],
    }
    for i in range(args.n):
        cw, enc_raw = encodings[i]
        trial = {
            "message": messages[i],
            "codeword": "".join(str(b) for b in cw) if cw else None,
            "valid_encoding": cw is not None and cw in COSETS[messages[i]],
            "enc_raw": enc_raw,
            "decoders": {},
        }
        for dec_name, results in all_decoder_results.items():
            decoded, n_errs = results[i]
            trial["decoders"][dec_name] = {
                "decoded": decoded,
                "n_errors": n_errs,
                "correct": decoded == messages[i] if decoded is not None else None,
            }
        output["trials"].append(trial)

    os.makedirs(os.path.join(ROOT, "results"), exist_ok=True)
    suffix = f"_p{args.p}" if args.p > 0 else ""
    outpath = os.path.join(ROOT, "results", f"wiretap_coding{suffix}.json")
    with open(outpath, "w") as f:
        json.dump(output, f, indent=2)
    print(f"\nSaved to {outpath}")

    http_client.close()


if __name__ == "__main__":
    main()
